language: python
python:
    - "2.6"
    - "2.7"

install: pip install -r requirements.txt

before_script:
    - psql -c 'create database foo;' -U postgres

env: NORM_POSTGRESQL_URL=postgres://postgres@127.0.0.1:5432/foo

script: trial norm